#!/bin/bash
pkill -P $(pgrep -f xdocorner)
# read config file
conf="$HOME/.config/xdocorner.ini"

# parse config
get_val(){
    section=$1
    key=$2
    value=$(grep -A 3 "^\[$section\]" "$conf" | grep "^$key"| awk -F "=" '{print $2}')
    echo "$value"
}

locations=("top-left" "top-right" "bottom-left" "bottom-right" "top" "bottom" "left" "right")

for loc in "${locations[@]}"; do
    delay=$(get_val "$loc" "delay")
    cmd=$(get_val "$loc" "command")

    if [ -n "$cmd" ]; then
        echo -e "$loc $delay $cmd"
        # set up hot corner
        hotcorner="xdotool behave_screen_edge --delay $delay $loc exec $cmd"
        eval "$hotcorner" &
    fi

done
